apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fast-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: fast-api.isidroalfonsin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fast-api
                port:
                  number: 80